kind: ConfigMap
apiVersion: v1
metadata:
  name: server
data:
  application.properties: >-
    quarkus.http.ssl.certificate.key-store-file=/deployments/tls/keystore.p12

    quarkus.http.ssl.certificate.key-store-password=123423556

    quarkus.http.ssl.certificate.trust-store-file=/deployments/tls/truststore.p12
    
    quarkus.http.ssl.certificate.trust-store-password=123423556
