apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "issuer.fullname" . }}
  annotations:
    service.beta.openshift.io/inject-cabundle: "true"
  labels:
    {{- include "issuer.labels" . | nindent 4 }}
data: {}
