# Default values for issuer.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

baseDomain: unconf.io

serviceAccount:
  create: true
  annotations: {}
  name: "issuer"

issuer:
  create: false
  server: https://vault-internal.hashicorp.svc.cluster.local:8200
