apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: client
spec:
  commonName: client.app-dev.unconf.io
  dnsNames:
    - client.app-dev.unconf.io
    - client-app-dev.apps.cluster-7bcd.7bcd.sandbox334.opentlc.com
    - client.app-dev.svc
  issuerRef:
    name: vault-issuer-vault
  secretName: client
  keystores:
    pkcs12:
      create: true
      passwordSecretRef:
        key: password
        name: client-keystore-pass

