apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: client
spec:
  commonName: client.${jkube.namespace}.unconf.io
  dnsNames:
    - client.${jkube.namespace}.unconf.io
    - client-${jkube.namespace}.apps.cluster-7bcd.7bcd.sandbox334.opentlc.com
    - client.${jkube.namespace}.svc
  issuerRef:
    name: ${jkube.namespace}-issuer-vault
  secretName: client
  keystores:
    pkcs12:
      create: true
      passwordSecretRef:
        key: password
        name: client-keystore-pass

